#!/usr/bin/env bash

/usr/local/bin/limelight -m config width 2

# dont color inactive windows
/usr/local/bin/limelight -m config normal_color 0xaa000000
/usr/local/bin/limelight -m config active_color 0xffebdbb2
