#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise

yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                off
yabai -m config window_border                off
yabai -m config active_window_border_color   0xffebdbb2
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config window_border_width          4
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# "monocle" mode for space 1
~/.bin/yabai-monocle 1

yabai -m signal --add event=space_changed \
    action="limelight -m config active_color 0xffebdbb2" \
    label=reborder-after-clear

# borders are timing out oddly (being redrawn behind app windows?) for me.
# these signals to toggle borders off/on on window change seem to resolve issue.

# borders are doing weird things in yabai right now. disable until fixed.
# yabai -m signal --add event=application_front_switched \
#     action="yabai -m config window_border off; yabai -m config window_border on" \
#     label=window-border-reset-front_switched
#
# yabai -m signal --add event=window_focused \
#     action="yabai -m config window_border off; yabai -m config window_border on" \
#     label=window-border-reset-focused

# float system apps
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Installer$" manage=off

# float user apps
yabai -m rule --add app="^python$" manage=off
yabai -m rule --add app="^python$" manage=off
yabai -m rule --add app="^python3$" manage=off
yabai -m rule --add app="^Karabine$" manage=off
yabai -m rule --add app="^Karabiner" manage=off
# "app":"Karabiner-Elements",
# "title":"Karabiner-Elements Preferences",
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="^Harmony$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off

# manage work apps
yabai -m rule --add app="^Microsoft Outlook$" grid=90:160:1:1:158:88
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add app="^Pulse Secure$" manage=off
yabai -m rule --add app="^Oracle VM VirtualBox Manager$" manage=off
yabai -m rule --add app="^VirtualBox$" manage=off
yabai -m rule --add app="^VirtualBox VM$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off

# load limelight (window border system from yabai v2.4.3)
killall limelight >/dev/null
limelight >/dev/null &

echo "yabai configuration loaded.."
