#!/bin/sh

# macOS - issues ?
# on macOS, whatever is `exec`ing bspwmrc is just not finding bspc in PATH
# workflow:
#	open xQuartz.app (i.e. do not call `startx`)

PATH="/usr/local/bin:$PATH"

# why doesn't this work properly?
# notes:
# if sxhkd is started from here, new urxvts are fcked up
# if it's killed and started manually, they seem (inconsistent?) fine
# they have to be spawned from a terminal outside of X
sxhkd -c ~/.config/sxhkd/sxhkdrc
#sxhkd -c ~/.config/sxhkd/sxhkdrc >>~/.sxhkd_logs 2>&1 &

# necessary for xquartz?
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color		"#fbf1c7"
bspc config active_border_color			"#ebdbb2"
bspc config presel_feedback_color		"#fb4934"

bspc config border_width		2
bspc config window_gap			10

bspc config top_padding			45
bspc config bottom_padding		15
bspc config left_padding		15
bspc config right_padding		15

bspc config split_ratio			0.50

bspc config focus_follows_pointer true

bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config borderless_monocle   true
