#!/bin/bash

echo -e "                  \033[33m/"
echo -e "                 \\\\\\\\\\"
echo -e "                 ////"
echo -e "                 \\|\\|\\"
echo -e "                 ///// "
echo -e "           \033[37m|--===========--|"
echo -e "           ||             ||"
echo -e "           ||             ||=\\"
echo -e "           ||             ||  \\\\\\"
echo -e "           ||             ||   ||"
echo -e "           ||             ||  //"
echo -e "           ||             ||=/"
echo -e "           ||             ||"
echo -e "           ||=============||"
