#!/bin/bash

# requires `upower'
# working on archlinux; not sure about compatibility with other flavors

cachefile=/tmp/_kbd_brightness

# not sure about this?
max=255
min=0

[[ ! -e $cachefile ]] && echo '40' > $cachefile

max=255
min=0
inc=$(echo "$max / 20" | bc)

_set () {
    curr=$(cat $cachefile)

    if [[ $1 == "-i" ]]; then
        next=$((curr+inc))
        [[ $next -ge $max ]] && next=$max
    elif [[ $1 == "-d" ]]; then
        next=$((curr-inc))
        [[ $next -le $min ]] && next=$min
    elif [[ $1 == "--zero" ]]; then
        next=$min
    elif [[ $1 == "--max" ]]; then
        next=$max
    else
        return $min
    fi

    dbus-send --system --type=method_call --dest="org.freedesktop.UPower" "/org/freedesktop/UPower/KbdBacklight" "org.freedesktop.UPower.KbdBacklight.SetBrightness" int32:$next

    echo $next > $cachefile
}

_set $1
