#!/bin/bash

# script to show a scale of keyboard light brightness for polybar
# outputs one of three glyphs depending on keyb brightness,
# then a small symbol, then the percent.

cachefile=/tmp/_kbd_brightness

[[ ! -e $cachefile ]] && echo '40' > $cachefile

r0=""
r1=""
r2=""

res=$(echo "100 * $(cat $cachefile) / 255" | bc -l | sed 's/\..*//')

source ~/.cache/wal/colors.sh
printf "%%{F${color12}}"
if [[ $res -le 34 ]]; then
    printf "$r0"
elif [[ $res -le 67 ]]; then
    printf "$r1"
else
    printf "$r2"
fi
printf "%%{F-}"
printf " ⌸"
printf " $res\n"
