#!/bin/bash

# Easily create a simple shell.nix/default.nix file with buildInputs as shell args

printf "with import <nixpkgs> {};

with pkgs;
stdenv.mkDerivation rec {
  name = \"env\";
  buildInputs = [
"
while [[ $# -gt 0 ]]; do printf "    $1\n"; shift; done
printf "  ];

  shellHook = ''
  '';
}
"
