#!/bin/bash
# kill fricking ubersicht with its damn name

# KilL
_kill() {
    printf "Killing app (takes a few seconds) ...\n"
    osascript -e 'tell application "Übersicht" to quit'
}

_open() {
    printf "Starting app (takes a few seconds) ...\n"
    open -a /Applications/Übersicht.app
}

_toggle() {
    proc=$(ps aux|grep "Übersicht"|wc -l)
    if [[ $proc -gt 1 ]]; then
        _kill
    else
        _open
    fi
}

if [[ -n "$1" ]]; then
    case "$1" in
        -k|--kill)
            _kill
            ;;
        -r|--refresh)
            osascript -e 'tell application "Übersicht" to refresh'
            ;;
        -t|--toggle)
            _toggle
            ;;
        *)
            print "incorrect usage: -r|-k|-t"
            ;;
    esac
else
    # default usage: kill, wait, reopen
    _kill
    sleep 2
    _open
fi
