#!/bin/sh

# hotkey daemon, bar, terminal
sxhkd &
polybar center &
polybar right &
urxvtc &

# set up desktops (determine with xrandr -q)
bspc monitor -d I II III

# colors, sizes
bspc config focused_border_color	"#fbf1c7"
bspc config active_border_color		"#edbdb2"
bspc config presel_feedback_color	"#edbdb2"

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.50

# configs
# dont use these settings w/ polybar
#bspc config single_monocle       true
#bspc config gapless_monocle      true
#bspc config borderless_monocle   true

bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true
