#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           25 #tentatively large to support new zenbar
bspc config presel_feedback_color "#ff6666"

bspc config split_ratio          0.52

bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config borderless_monocle   true

bspc rule -a firefox desktop=^2
# url-launcher ? /Applications/Firefox.app/Contents/MacOS/firefox

# panel &
