#!/bin/sh

# hotkey daemon and bar
sxhkd &
#$HOME/.config/polybar/launch.sh 2>/dev/null
# conky's not working yet, but rofi is (time in default modi)
# you know actually lets try to get conky going !

# set up desktops
bspc monitor -d I II III IV V

# colors, sizes
bspc config focused_border_color	"#fbf1c7"
bspc config active_border_color		"#edbdb2"
bspc config presel_feedback_color	"#edbdb2"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50

# configs
bspc config single_monocle       true
bspc config gapless_monocle      true
bspc config borderless_monocle   true

bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	true
