# don't bother with fiddling, just select ALL errors.
# select = ["E", "F", "C90", "I", "N", "ICN"]
lint.select = ["ALL"]

lint.ignore = [
  "ANN101",    # Missing type annotation for `self` in method
  "ERA001",    # Found commented-out code
  "COM812",    # missing trailing commas (conflicts with formatter)
  "D100",      # missing docstring in public module
  "D105",      # Missing docstring in magic method
  "D203",      # one-blank-line-before-class (prefer D212 no-blank-line-before-class)
  "D213",      # multi-line-summary-second-line (prefer D212 multi-line-summary-first-line)
  "ISC001",    # single line implicit str concat (conflicts with formatter)
  "T20",       # flake8-print
  "UP006",     # deprecated-collection-type (e.g. use `list` instead of `typing.List`)
]

line-length = 100

[lint.per-file-ignores]
"test_*.py" = [
  "D103",      # Missing docstring in public function
  "ANN201",    # Missing return type annotation for public function `{}`
  "INP001",    # File `{}` is part of an implicit namespace package. Add an `__init__.py`.
  "S101",      # Use of `assert` detected
  "PLR2004",   # Magic value used in comparison, consider replacing 526 with a constant variable
]

"__init__.py" = [
  "F401",      # imported but unused
]

"*.ipynb" = [
  "I",         # import order
  "F401",      # imported but unused
  "B018",      # useless expression
]

# can i make this set noexpandtab for this file?
# vim:tw=78:ts=8:noet:ft=toml:norl:
