#!/bin/bash

# put some fzf-related overrides here too
export FZF_DEFAULT_COMMAND='fd -I --ignore-file ~/.gitignore_global --type file --color=always'
# --color options modified from what pywal generates by default
export FZF_DEFAULT_OPTS='
    --ansi --bind "ctrl-p:preview-up,ctrl-n:preview-down"
    --color fg:7,hl:1,fg+:2,hl+:255
    --color info:3,marker:1,pointer:3,spinner:1,gutter:7
'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND --ignore-file ~/.gitignore_global"
export FZF_ALT_C_COMMAND='fd -t d --ignore-file ~/.gitignore_global'

# requires overriding fzf-history-widget (see below)
# immediately execute a line with c-x (or inspect with enter, as usual)
export FZF_CTRL_R_OPTS="--expect=ctrl-x"
export FZF_CTRL_T_OPTS="--border"

__git_log () {
    # format str implies:
    #  --abbrev-commit
    #  --decorate
    git log \
        --color=always \
        --graph \
        --all \
        --date=short \
        --format="%C(bold blue)%h%C(reset) %C(green)%ad%C(reset) | %C(white)%s %C(red)[%an] %C(bold yellow)%d"
}

# fuzzy find file content (open results with <Enter>)
fgr() {
	local line
    line=$(
        ggrep --line-buffered --color=never -r '' * |
        fzf --nth=1,2
    ) && ${EDITOR:-vim} $(echo "${line%%:*}")
}

# fuzzy completion with 'z' when called without args
unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && zshz "$*" && return
  cd "$(zshz -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}

# ftags - search ctags
ftags() {
	local line
    [ -e tags ] &&
        line=$(
            awk 'BEGIN { FS="\t" } !/^!/ {print toupper($4)"\t"$1"\t"$2"\t"$3}' tags |
            cut -c1-80 | fzf --nth=1,2
        ) && ${EDITOR:-vim} $(cut -f3 <<< "$line") -c "set nocst" \
            -c "silent tag $(cut -f2 <<< "$line")"
}

# pass completion suggested by @d4ndo (#362) (slightly modified)
_fzf_complete_pass() {
  _fzf_complete '+m' "$@" < <(
    local pwdir=${PASSWORD_STORE_DIR-~/.password-store/}
    find "$pwdir" -name "*.gpg" -print |
        sed -e "s#${pwdir}/\{0,1\}##" |
        sed -e 's/\(.*\)\.gpg/\1/'
  )
}

# fshow_preview - git commit browser with previews
fshow_preview() {

	local _gitLogLineToHash="echo -n {1} | head -1"
	local _viewGitLogLine="$_gitLogLineToHash | xargs -I % sh -c 'git show --color=always % | diff-so-fancy'"
	local _viewPreview="$_gitLogLineToHash | xargs -I % sh -c '(git show --stat --color=always % && echo '' && git show --color=always %) | diff-so-fancy'"

    git log --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr% C(auto)%an" |
        fzf --no-sort --reverse --tiebreak=index --no-multi \
            --ansi --preview="$_viewPreview" \
                --header "enter to view, alt-y to copy hash" \
                --bind "enter:execute:$_viewGitLogLine   | less -R" \
                --bind "alt-y:execute:$_gitLogLineToHash | pbcopy"
}

_fzf_complete_git() {
    ARGS="$@"

    # these are commands I commonly call on commit hashes.
    # cp->cherry-pick, co->checkout

    if [[ $ARGS == *'git cp'* || \
          $ARGS == *'git cherry-pick'* || \
          $ARGS == *'git co '* || \
          $ARGS == *'git checkout'* || \
          $ARGS == *'git reset'* ]]; then
        _fzf_complete "--reverse --multi" "$@" < <(__git_log)
    else
        eval "zle ${fzf_default_completion:-expand-or-complete}"
    fi
}

_fzf_complete_git_post() {
    sed -e 's/^[^a-z0-9]*//' | awk '{print $1}'
}

gh () {
    # fuzzy search commits from `git log`
    git rev-parse --is-inside-work-tree > /dev/null 2>&1 || return

    local item
    __git_log |
    fzf --height '50%' --border --ansi --no-sort --reverse --multi \
        --delimiter="\|" --nth="-1" |
    grep -o "[a-f0-9]\{7,\}" |
    head -n1 |
    while read -r item; do echo -n "${(q)item} "; done
}

fgst () {
    # fuzzy search files from `git status`
    git rev-parse --is-inside-work-tree > /dev/null 2>&1 || return

    header="$(git -c color.status=always status -uno --short --branch | head -n1)"

    command git -c color.status=always status -uno --short |
        FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} \
            --reverse \
            $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" \
            fzf -m --preview="git diff --color=always {-1}" --header="$header" |
        while read -r item; do
        echo "$item" | awk '{print $NF}'
    done
}

if [[ $SHELL == *"zsh" ]]; then
    fzf-gh-widget () { local result="$(gh)"; zle reset-prompt; LBUFFER+="$result" ; }
    zle -N fzf-gh-widget
    bindkey '^G^G' fzf-gh-widget

    fzf-git-status-widget () { local result="$(fgst)"; zle reset-prompt; LBUFFER+="$result"; }
    zle -N fzf-git-status-widget
    bindkey '^G^S' fzf-git-status-widget
fi


# copied+modified from FZF install: shell/key-bindings.zsh
# see:
# - https://github.com/junegunn/fzf/issues/477
# - checkout out https://github.com/junegunn/fzf/pull/1492
# CTRL-R - Paste the selected command from history into the command line
fzf-history-widget() {
  local selected num
  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  selected=( $(fc -rl 1 | perl -ne 'print if !$seen{(/^\s*[0-9]+\**\s+(.*)/, $1)}++' |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort,ctrl-z:ignore $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
  local ret=$?
  if [ -n "$selected" ]; then
      local accept=0
      if [[ $selected[1] = ctrl-x ]]; then
          accept=1
          shift selected
      fi
    num=$selected[1]
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
      [[ $accept = 1 ]] && zle accept-line
    fi
  fi
  zle reset-prompt
  return $ret
}
zle     -N   fzf-history-widget
bindkey '^R' fzf-history-widget
